@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

SHOW_PERSON_PORTRAIT()
LAYOUT_LEFT_RIGHT()

title Diagrama de contexto do SpotMusic

Person(usuario, "Usuário do SpotMusic", "Usuário com conta ativa")

System(mobile, "mobile", "playlists e musicas")

Rel(usuario, mobile, "Acessa/consome")

@enduml
